name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Verificar se já existe uma implantação anterior (e cancelar se necessário)
      - name: Cancel previous deployment if it exists
        uses: actions/github-script@v6
        with:
          script: |
            // Pegue a lista de implantações anteriores
            const { data: deployments } = await github.rest.pages.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Verifica se há implantações e se elas já foram concluídas
            if (deployments.length > 0) {
              const latestDeployment = deployments[0];

              // Se a implantação foi concluída com sucesso, ignore o cancelamento
              if (latestDeployment.status === 'success') {
                console.log('Última implantação já foi concluída com sucesso. Não é necessário cancelar.');
              } else {
                // Caso contrário, cancele a implantação
                await github.rest.pages.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: latestDeployment.id
                });
                console.log('Implantação anterior cancelada.');
              }
            }

      # Passo 2: Ação de deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
