name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Verificar e cancelar implantação anterior (se necessário)
      - name: Cancel previous deployment if it exists
        uses: actions/github-script@v6
        with:
          script: |
            const { data: deployments } = await github.rest.pages.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            if (deployments.length > 0) {
              const latestDeployment = deployments[0];

              if (latestDeployment.status !== 'success') {
                console.log('Deployment already completed, no need to cancel.');
              } else {
                await github.rest.pages.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: latestDeployment.id
                });
                console.log('Canceled previous deployment.');
              }
            }

      # Passo 2: Ação de deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
